travis:
  secure:
    BINSTAR_TOKEN: NiP3670Wfr5Tvy1IdhtD2dxwyCfnrzPJD7qYbm8jgyKiROMi6kSQiH31G1mHgcFzrIJSXaSNanYfCOm54yJ19TqLp5o1jmhkidJ46bg7k3myMjurH3FcTJIPO4Fwp8b1o8AVyWctoeV+tRaVyMNCV9SDoDZ8GyCFttJux1B0IOAgF2Km2zWTqAT/6bqcU1y3LYxlsbGm8+GDTLLAk8M/vV3YlyNDIl+1WPlYY4zAsDkmyYkz4Ij9+XoRLKxIHdT5bEYbgAIT45xC3Q0nLv6MjhRq9vP1OwE0dbJmfTd0kqFn3CBnsnMi4181bCzup/fH3/Qh3xGA2EDNLOy9jPdV9PPGw00a5Q9akIZgIrHKlOWu3HlxRlB3H1Onipag1/vXTKdymGGJb3mSDrJE03kYUJkSrfOGade5mMkFKL4c5XCPahZkx/sJPyKN7ltNGDwx0GNwzsCRtQGrOSAXsqcRhV+7FxPG/QSQRhpWSElUt4paYAAf0vNiNQbVLKRBQviudgK+GS5lnnoqD0Z1CAPvpA73bRpX4oa8Y7AnHuIuAjUT2luiBTuxNhYwSIMQvljbKawS1eXVk+pJjoNimzz3GFjh0pi3/5AcWDVPcs0c1Ub3yFakjyG+UTBNQ+hBK8HZDh3YznZKqCLhZdbClGUJuQm4comAs2gh70E4YVwbSFA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
