travis:
  secure:
    BINSTAR_TOKEN: lEOGVo/zRgzg5XKEVvEfcV48FOTISgH/KU/K5Pj7Y7jXt8N7oBAd46N+UjF3sfpOJuHL+jpdelEefAzgF3hTgj0t+nuZuYzfusKxOzrvKuB9GUSUhvxqfGEs9WScjgiCp0Ln14kPDI2e5j77wgGDGS7hghJJNoO3wcCWdc6QHf/NVA0xKzLp5swHCgGYvxdcmZXUjQyZsY3GQwJw7RnWoAQRhxLr7+1ONHbcokdFrIUwBZ+R2G5UpFXHsIkFYaViFb2n30MqrICyPdekMvRD3CvQ+P9WjlJ8F+Ac7vfUNqEu+inQqZqy6wetlzPOkD8ZjG6VRNKqgDCz3UHCXYx1tFcYLGSTOaa9BOhcvyPTFrSW9UFsb7K+4pX381Q/5rOz+GRdpvBlmDKC1bEgtLuF+Rr8XIB8bR8tWXzu6qH7wBr7uQxljsumw7KAC9f2v9wOXaQhjFmoqQG/V3AIYA/T0CG7Z7SJOXXpeFzhlB1aZiXsQOpu4ZaDDzL5QnpzGUECuUZTQ34QZ0W2b8igd0roCwG3LwW6EmcgSnijjNLuz6eFkD1kyzA2F2Bw4BH92Pft18FCTUC8cTS1JS4V8XrCf3FBQ8DiuIMqAhO4Xt2qYvtykAh3osSSrNh0SAVl7cU356+E5IbC1C3CFopxTUNSVstAofi4s9Eghpx2Hq/rZys=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
