appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Xm0Iy/Y5Csk0KKIP0A1H5C9c+4RK9ftCVPetWm14n1XFK2z5sKKnqu2CqUfYLXAEd+B8u31AgWy+jObdQwMP4+1XEd7UWLbFOh5hVqftSyx/OQuq3oudB2nsFCr6yk0zKei6V0hgPoQhT5fpBn4lR2GDluo6AEDAS4UEC6MrRLppJzkbzjctDXOUp+Mgh28nzqWSO1z6DP0LcaRakPh8h2UwJsQIWsnjkyuWkzTnFFOnzBrGlf8s+aCcd/Yxnqn6jnTcu+mKa1EqjXt2GnR0XWY7avKEt+8LqhENyAPWYHTsMCnoGVovEtyQexZlaj1aGfAih9KgVjt88HWvx05oEvZmzvLYqjO6u5MsS35Wwaz9AsMUYEGBYxX1iebwvDg6t0V9CdCfSue1Cl3Ay0rTb5vcC8uFH/705EX7DPrYuzfif8LeWpo/UN6LTbbr2AXLKSXBDaBB6l7sqDMqlLIDW9DxvPhg4VGnaDPEpyaLNJOL+5h/3ES79MYyq0M4bKRSAoWoojjQMtzVamnYA7DCOzr7CWsP+bJZsmN37BTX7t9n1BNn7CSrcqrN7R/mz101Xx/N+3UgzMFdi5/ix+nEqAnQzrbDzCgoy8KpOw8sKhrqo+3zXtbvkOvzCLNG8LAIAKSzgUwMMBTuvQPzhfNM1Db3WHMtg1SOFOkg6kmlEAg=
